### ISSUE TITLE
Free theorems modernization roadmap

### ISSUE THREAD

**Issue by alexfmpe** [ichistmeinname/free-theorems#4]
- [x] Building with newer GHC: #2
- [x] Exposing support for higher-ranked types: #3
- [ ] Handling incomplete pattern matches
- [ ] New hackage release
- [ ] Potentially upstream into ghci 

There's 30-40 incomplete patterns laying around. For some of them it's obvious what to do, but in general I've been mostly doing `throwError` or documenting with `error`, depending on what's already there. Hardly ideal but still better than `Non-exhaustive patterns in function foo`, which is what we currently get for (intentionally or not) unsupported operations.

I wanted to port *just* #3 to @nomeata's version to get one last useful/releasable step before the big merge/jump, but it required also porting the work getting `haskell-src-exts` to build for newer ghc, so meh.

I do wonder if it makes sense for `free-theorems` to keep living as a standalone thing that has its own mini haskell AST types in addition to the ones in `haskell-src-exts` (which is now in life support). Would it be more at home in `ghci` under `:i` or so? Maybe it could be a google summer of code or haskell foundation project.
After all, the compiler already has everything in scope, and squeezing every bit of reasoning based on types alone is textbook haskell. I'm not sure if the theorems could also be useful for automatically obtaining rewrite rules or if that always needs human curation.

cc @ichistmeinname @nomeata

**Comment by nomeata** [comment]
> New home (standalone repo?)

What's wrong with the present repo?

**Comment by alexfmpe** [comment]
Well nothing per-se. 
I thought you planned to make a new one? https://github.com/nomeata/free-theorems-static-webui/pull/3#issuecomment-1361272449
"New home" was also meant to cover the "should this be upstreamed into ghci or something" point - edited for clarity.

**Comment by nomeata** [comment]
> I thought you planned to make a new one? 

Only if noone else does it :-). It seems that right now you are most motivated, so why not keep it here?

**Comment by ichistmeinname** [comment]
@alexfmpe Would you mind setting up a ci pipeline to run the project with some appropriate versions of GHC? I would then be happy to merge the PRs if they pass the compilation step.

**Comment by alexfmpe** [comment]
@ichistmeinname done: https://github.com/ichistmeinname/free-theorems/pull/6
